# application build image
FROM openJDK:8

# environment variable setting for apt-get error prevention 
ENV DEBIAN_FRONTEND=noninteractive

# essential utility install
RUN apt-get update && apt-get install -y unzip wget vim

# install gradle 7.2 & environment variable setting
ADD https://services.gradle.org/distributions/gradle-7.2-all.zip /opt/
RUN unzip /opt/gradle-7.2-all.zip -d /opt/gradle
ENV GRADLE_HOME /opt/gradle/gradle-7.2
ENV PATH $GRADLE_HOME/bin:$PATH

# JENKINS environment variable setting
ARG http_port=8080
ARG agent_port=50000
ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000
ENV JENKINS_HOME /var/jenkins_home
ENV JENKINS_SLAVE_AGENT_PORT ${agent_port}
ARG REF=/usr/share/jenkins/ref
ENV REF $REF



# make directory for JENKINS
RUN mkdir -p $JENKINS_HOME \
 && chown ${uid}:${gid} $JENKINS_HOME \ 
 && groupadd -g ${gid} ${group} \ 
 && useradd -d /var/jenkins_home -u ${uid} -g ${gid} -m -s /bin/bash ${user}

