# application build image
FROM openJDK:8

# environment variable setting for apt-get error prevention 
ENV DEBIAN_FRONTEND=noninteractive

# essential utility install
RUN apt-get update && apt-get install -y unzip wget vim

# install gradle 7.2 & environment variable setting
ADD https://services.gradle.org/distributions/gradle-7.2-all.zip /opt/
RUN unzip /opt/gradle-7.2-all.zip -d /opt/gradle
ENV GRADLE_HOME /opt/gradle/gradle-7.2
ENV PATH $GRADLE_HOME/bin:$PATH

# Add Tini (process optimize on container)
# gpg = encryption tool
ENV TINI_VERSION v0.19.0
COPY tini_pub.gpg ${JENKINS_HOME}/tini_pub.gpg
RUN curl -fsSL https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-static-$(dpkg --print-architecture) -o /sbin/tini \
 && curl -fsSL https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-static-$(dpkg --print-architecture).asc -o /sbin/tini.asc \
 && gpg --no-tty --import ${JENKINS_HOME}/tini_pub.gpg \
 && gpg --verify /sbin/tini.asc \
 && rm -rf /sbin/tini.asc /root/.gnupg \
 && chmod +x /sbin/tini

