version: '3.8'

services:
 db:
  image: mysql:8.0.2
  volumes:
    - /home/wip-dev/data:/var/lib/mysql
    - /home/wip-dev/ssl:/etc/ssl/mysql
  env_file:
   - ./wip-env.env

 main:
  image: 2mukee/wip-main-deploy:1.1
  depends_on:
   - db
  environment:
   - TZ=Asia/Seoul
  ports:
   - 18080:8080

 dl:
  image: 2mukee/wip-dl-deploy:1.1
  depends_on:
   - main
  environment:
   - TZ=Asia/Seoul