version: '3.8'

services:
 db:
  image: 2mukee/wip-db
  volumes:
   - /home/wip-dev/data:/var/lib/mysql
  command: --default-authentication-plugin=mysql_native_password
  env_file:
   - ./wip-env.env

 main:
  image: 2mukee/wip-main
  depends_on:
   - db
  environment:
   - TZ=Asia/Seoul
  ports:
   - 18080:8080

 dl:
  image: 2mukee/wip-dl-deploy
  depends_on:
   - main
  environment:
   - TZ=Asia/Seoul